'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  LineChart,
  Line
} from 'recharts';
import { 
  TrendingUp, 
  FolderKanban, 
  FileText, 
  Clock,
  ArrowUpRight
} from 'lucide-react';

interface DashboardStatsProps {
  projects: Array<{
    id: string;
    name: string;
    sector: string;
    status: string;
    createdAt: string;
    generatedDoc?: {
      status: string;
      canvases: Array<{ canvasType: string }>;
    } | null;
  }>;
  totalDocs: number;
  exportsUsed: number;
}

const COLORS = ['#10b981', '#3b82f6', '#f59e0b', '#ef4444', '#8b5cf6', '#ec4899'];

const SECTOR_LABELS: Record<string, string> = {
  TECH: 'Tech / Digital',
  AGRO: 'Agriculture',
  AGRO_ALIMENTAIRE: 'Agro-alimentaire',
  SERVICES: 'Services',
  COMMERCE: 'Commerce',
  AUTRE: 'Autre',
};

export function DashboardStats({ projects, totalDocs, exportsUsed }: DashboardStatsProps) {
  // Calculate stats
  const completedProjects = projects.filter(p => p.status === 'COMPLETED').length;
  const inProgressProjects = projects.filter(p => p.status === 'IN_PROGRESS' || p.status === 'GENERATING').length;
  const draftProjects = projects.filter(p => p.status === 'DRAFT').length;

  // Projects by sector for pie chart
  const sectorCounts: Record<string, number> = {};
  projects.forEach(p => {
    sectorCounts[p.sector] = (sectorCounts[p.sector] || 0) + 1;
  });
  const sectorData = Object.entries(sectorCounts).map(([sector, count]) => ({
    name: SECTOR_LABELS[sector] || sector,
    value: count,
  }));

  // Projects by month for line chart
  const last6Months = Array.from({ length: 6 }, (_, i) => {
    const date = new Date();
    date.setMonth(date.getMonth() - (5 - i));
    return date.toLocaleDateString('fr-FR', { month: 'short' });
  });

  const projectsByMonth = last6Months.map((month, i) => {
    const count = projects.filter(p => {
      const projectDate = new Date(p.createdAt);
      const targetDate = new Date();
      targetDate.setMonth(targetDate.getMonth() - (5 - i));
      return projectDate.getMonth() === targetDate.getMonth() && 
             projectDate.getFullYear() === targetDate.getFullYear();
    }).length;
    return { month, projets: count };
  });

  // Documents generated by type
  const docsByType = [
    { type: 'BMC', count: projects.filter(p => p.generatedDoc?.canvases?.some(c => c.canvasType === 'BUSINESS_MODEL_CANVAS')).length },
    { type: 'Lean Canvas', count: projects.filter(p => p.generatedDoc?.canvases?.some(c => c.canvasType === 'LEAN_CANVAS')).length },
    { type: 'Business Plan', count: projects.filter(p => p.generatedDoc?.status === 'COMPLETED').length },
  ];

  return (
    <div className="space-y-6">
      {/* Summary Cards */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Projets Totaux</CardTitle>
            <FolderKanban className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{projects.length}</div>
            <div className="flex items-center text-xs text-muted-foreground">
              <ArrowUpRight className="w-3 h-3 text-green-500 mr-1" />
              <span className="text-green-500">+{inProgressProjects}</span> en cours
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Documents Générés</CardTitle>
            <FileText className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{totalDocs}</div>
            <div className="text-xs text-muted-foreground">
              BMC, Lean Canvas, Business Plans
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Taux de Complétion</CardTitle>
            <TrendingUp className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {projects.length > 0 ? Math.round((completedProjects / projects.length) * 100) : 0}%
            </div>
            <Progress 
              value={projects.length > 0 ? (completedProjects / projects.length) * 100 : 0} 
              className="mt-2 h-2"
            />
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Temps Économisé</CardTitle>
            <Clock className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">~{completedProjects * 20}h</div>
            <div className="text-xs text-muted-foreground">
              vs création manuelle
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Charts Row */}
      <div className="grid gap-6 lg:grid-cols-2">
        {/* Projects by Month */}
        <Card>
          <CardHeader>
            <CardTitle>Activité Mensuelle</CardTitle>
            <CardDescription>Projets créés au cours des 6 derniers mois</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="h-[250px]">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={projectsByMonth}>
                  <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
                  <XAxis dataKey="month" className="text-xs" />
                  <YAxis className="text-xs" />
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: 'hsl(var(--background))', 
                      border: '1px solid hsl(var(--border))',
                      borderRadius: '8px'
                    }}
                  />
                  <Line 
                    type="monotone" 
                    dataKey="projets" 
                    stroke="hsl(var(--primary))" 
                    strokeWidth={2}
                    dot={{ fill: 'hsl(var(--primary))', strokeWidth: 2 }}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>

        {/* Projects by Sector */}
        <Card>
          <CardHeader>
            <CardTitle>Répartition par Secteur</CardTitle>
            <CardDescription>Vos projets par secteur d'activité</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="h-[250px]">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={sectorData}
                    cx="50%"
                    cy="50%"
                    innerRadius={60}
                    outerRadius={90}
                    paddingAngle={5}
                    dataKey="value"
                    label={({ name, percent }) => `${name} (${(percent * 100).toFixed(0)}%)`}
                    labelLine={false}
                  >
                    {sectorData.map((_, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: 'hsl(var(--background))', 
                      border: '1px solid hsl(var(--border))',
                      borderRadius: '8px'
                    }}
                  />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Documents Chart */}
      <Card>
        <CardHeader>
          <CardTitle>Documents Générés par Type</CardTitle>
          <CardDescription>Répartition de vos documents business</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="h-[250px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={docsByType} layout="vertical">
                <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
                <XAxis type="number" className="text-xs" />
                <YAxis dataKey="type" type="category" className="text-xs" width={100} />
                <Tooltip 
                  contentStyle={{ 
                    backgroundColor: 'hsl(var(--background))', 
                    border: '1px solid hsl(var(--border))',
                    borderRadius: '8px'
                  }}
                />
                <Bar dataKey="count" fill="hsl(var(--primary))" radius={[0, 4, 4, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </CardContent>
      </Card>

      {/* Project Status Overview */}
      <Card>
        <CardHeader>
          <CardTitle>État des Projets</CardTitle>
          <CardDescription>Vue d'ensemble du statut de vos projets</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid md:grid-cols-3 gap-4">
            <div className="p-4 border rounded-lg text-center">
              <div className="text-3xl font-bold text-green-500">{completedProjects}</div>
              <div className="text-sm text-muted-foreground">Complétés</div>
              <div className="mt-2 h-2 bg-muted rounded-full overflow-hidden">
                <div 
                  className="h-full bg-green-500 transition-all" 
                  style={{ width: `${projects.length > 0 ? (completedProjects / projects.length) * 100 : 0}%` }}
                />
              </div>
            </div>
            <div className="p-4 border rounded-lg text-center">
              <div className="text-3xl font-bold text-blue-500">{inProgressProjects}</div>
              <div className="text-sm text-muted-foreground">En Cours</div>
              <div className="mt-2 h-2 bg-muted rounded-full overflow-hidden">
                <div 
                  className="h-full bg-blue-500 transition-all" 
                  style={{ width: `${projects.length > 0 ? (inProgressProjects / projects.length) * 100 : 0}%` }}
                />
              </div>
            </div>
            <div className="p-4 border rounded-lg text-center">
              <div className="text-3xl font-bold text-yellow-500">{draftProjects}</div>
              <div className="text-sm text-muted-foreground">Brouillons</div>
              <div className="mt-2 h-2 bg-muted rounded-full overflow-hidden">
                <div 
                  className="h-full bg-yellow-500 transition-all" 
                  style={{ width: `${projects.length > 0 ? (draftProjects / projects.length) * 100 : 0}%` }}
                />
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
